### ISSUE TITLE
Windows 11: File above 2Gb Issue

### ISSUE THREAD

**Issue by DBenS** [end2endzone/ShellAnything#104]
Hi Antoine, how are you going? I hope very well.

In WIndows 11 if I try to "action" on any file above 2Gb size, the menu still doesn't appear. Below this limit, everything runs 100%.
I'm running the latest 0.70 version.

**To Reproduce**
1. Create a RAR/ZIP file grater than 2Gb
2. Open Windows Explorer and right-button over it.
3. See error

**Environment**
 - OS: Windows 11
 - Version Edição	Windows 11 Home (21H2) ver 22000.493

https://user-images.githubusercontent.com/13090884/153729585-322855a1-d54a-410a-829e-ed4bd208169a.mp4

**Comment by DBenS** [comment]
Ops!

Just EXIT from the account and entry again seems to be solved this problem - so, it is NOT a bug, but a kind of Windows cache of the older version.

I apologize for this

**Comment by end2endzone** [comment]
Hi. The latest version (0.7.0) has fixed 2 issues that you submitted: #96 (Problems with Files > 2Gb) and #97 (Files and folders together do not start MENU). It also have many more features. You can take a look at everything new in the release notes.

If you like ShellAnything, please star the project 👍

Also watch out for the next version which will introduce plugins!
