### ISSUE TITLE
RegEx support for pattern property

### ISSUE THREAD

**Issue by arathburgos05** [end2endzone/ShellAnything#128]
-----------> **[Solved with workaround shown in other comment]**

**Is your feature request related to a problem? Please describe.**
First of all great work! I'm impressed of the flexible, powerful and complete documentation of the program. I've started to use the plugin like 2 hours ago. I have this situation:
- I want to filter multiple selected folders to enable/disable the row. For example if the selected folder has "ab" then it appears if not then it doesn't appear.

I tried in this way:
`<visibility class="directory" pattern="*ab*"/>`

However, it doesn't work for the next case:
C:\SW\anyFolderWithabPart\otherFolder\02_Make → It shouldn't appear because selected folder doesn't have the letters "ab" (02_Make).

Reason is that pattern checks in parent folders (all path).

**Describe the solution you'd like**
Support for RegEx would solve the problem. Basically detecting the last backslash and the applying the filter. Maybe there are more ways to solve it but I'm out of ideas.

**Describe alternatives you've considered**
Maybe there are options that I haven't found in the documentation to deal directly with foldername and not with parents folder (or full path) in pattern.

**Additional context**
This is my full XML file:
`<root>
  <shell>
  
    <menu separator="true" />
    
    <menu name="Elektrobit Tools Helper">
      <icon path="C:\SW\ab-icons\ab.ico" index="0" />
      <menu name="Print files paths">
        <visibility class="directory" pattern="*ab*"/>
        <icon path="C:\SW\ab-icons\ab-plugin.ico" index="0" />
        <actions>
          <property name="selection.multi.separator" value="&quot; &quot;" />
          <exec path="C:\Windows\System32\cmd.exe" arguments="/c call C:\print_args.bat /c &quot;${selection.filename}&quot;"/>
          <property name="selection.multi.separator" value="${line.separator}" />
        </actions>
      </menu>

    </menu>

    <menu separator="true" />
    
  </shell>
</root>`

**Comment by arathburgos05** [comment]
I would like to ask also if it possible to use this attribute with the current selected folder/path.
`<visibility exists="C:\Program Files (x86)\Microsoft Office\Office16\WINWORD.EXE" />`

For example, If I select this folder **D:\Projectspace\Projects\projectA**

I would like to use something like
`<visibility exists=".\build" />`

to check if **D:\Projectspace\Projects\projectA\build** exists.

Thanks for your attention. Regards :)

**Comment by arathburgos05** [comment]
Solved using:
`<visibility class="directory" exprtk="'${selection.path}' ilike '\*\*ab*'"/>`

anyways I would like to know if there is another way to do it better or clearer.

**Comment by arathburgos05** [comment]
Solved using:
`<visibility class="directory" exprtk="'${selection.path}' ilike '\*\*ab*'"/>`
or
<visibility class="directory" exprtk="'${selection.filename}' ilike '*ab*'"/>

anyways I would like to know if there is another way to do it better or clearer. (apply it just a folder NOT a file with *ab* content in the selected folder) and if there is support for RegEx in some way.

**Comment by arathburgos05** [comment]
I take this opportunity to ask if I can also condition the horizontal separators so that they disappear according to the conditions I define (or link it with another row). To prevent it from looking like this:
![image](https://github.com/end2endzone/ShellAnything/assets/25379464/56aa43b7-148a-47d2-857a-78d64fabaed1)

I tried with this one but it didn't work :(
`      <menu separator="true"/>
      <visibility class="directory" exists="${selection.path}\src;${selection.path}\test"/>
      <menu/>`

Regards.

**Comment by arathburgos05** [comment]
Solved using:
`<visibility class="directory" exprtk="'${selection.path}' ilike '\*\*ab*'"/>`
or
<visibility class="directory" exprtk="'${selection.filename}' ilike '*ab*'"/>

Sorry for opening this PR unnecessary.

**Comment by end2endzone** [comment]
Thank you for the feedback. It is much appreciated.

I am glad you found an alternate option to RegEx. Exprtk expressions are not Regular Expressions but they are similar. I think at the time of the implementation, I was looking for something that would work as close to Dos command such as `dir *.exe`.

Regular expression would be a great addition to Shell Anything. It could be added in a future update. Feel free to open a new issue for requesting this requirement. However, I must say that my free time is quite limited now and I do not think I will have time to implement such a feature in the next 6-12 months.

**Comment by arathburgos05** [comment]
For the moment, I think this is not needed. In my opinion RegEx necessity is covered by Exprtk. I've updated the post and the format to clarify what was needed just for documentation purposes (that night I was tired and I didn't even know what I wanted 😆).

One question @end2endzone, does someone reported you that contextual menu open and closes suddenly sometimes? I'm not sure if this is a problem of my complex exprtk condition, a general problem with exprtk tool or another option.

Regards 👍

**Comment by end2endzone** [comment]
@arathburgos05, sorry for the late reply. I did not noticed the question since the issue was closed.
No, I am not aware of an issue that makes the menu open and close suddenly.

I know it is not a crash of Shell Anything. Shell Anything DLL is "linked" to the owner process which is Explorer.exe. In case of a crash of Shell Anything, your Explorer.exe process would also crash.

Shell Extension do not control when a menu is displayed or hidden. They provide/feed the menu new items to display. Your problem may be the result of incorrect/invalid content that your configuration files try to add to the menu. I would suggest [looking at your log files](https://github.com/end2endzone/ShellAnything/blob/master/UserManual.md#logging-support) or investigating you configuration files one by one using a trial and error approach.

If you find reproducing steps, or hints on how why this would occurs, I would gladly investigate. If so, please document your observations in a new issue.
