### ISSUE TITLE
Separator visibility options

### ISSUE THREAD

**Issue by GasDauMin** [end2endzone/ShellAnything#141]
I wanted to clarify if I understand correctly that the visibility of the separator is not controlled, if it is set, it will be set and there is no possibility to change it. If so, in this case, it would be very important to have the ability to control the visibility of the separator.

As is the case with me, I have described several menu items after the separator, but they are displayed under certain conditions (e.g., exceptions for file extensions, files, directories, etc.) and are not available in this context. Therefore, I would like to be able to control the separator itself.

![Separator](https://github.com/end2endzone/ShellAnything/assets/2140205/e20d6336-4664-4e3e-a5ca-57d7860be227)

**Comment by end2endzone** [comment]
You are correct. The visibility of the separator is not controlled. I think that it would be a good addition to ShellAnything.

I do not think it would be that hard to implement. Change the parser to parse _visibility/validity_ elements even when `separator="true"` is found. Change the menu renderer function [BuildMenuTree()](https://github.com/end2endzone/ShellAnything/blob/0.8.0/src/shellextension/CContextMenu.cpp#L244) to test for _visibility/validity_ even when `Menu::IsSeparator()` is true.

Would you be able to contribute again with this feature? I would gladly accept a pull request.

**Comment by GasDauMin** [comment]
I might be able to work again, but it's hard to say when, I was hoping there would be time to work at the time that I accidentally did a commit. But at the same time I started working on a second project, and there was no more free time for hobby coding, as much as I would like to :)

**Comment by GasDauMin** [comment]
However, I can see that it would not take much time to make the right change. I think I can do it. I'm just having trouble with the compilation, I've made the change completely but I can't test it, now I am finding out what is wrong. :D

![image](https://github.com/end2endzone/ShellAnything/assets/2140205/bd6f1eac-c302-4efe-8fd3-4f340694830e)
