### ISSUE TITLE
New logo icon

### ISSUE THREAD

**Issue by end2endzone** [end2endzone/ShellAnything#171]
**Is your feature request related to a problem? Please describe.**
The new icon is from a really old design. It is also 16x16 which is really low resolution for 4K screens. Windows menu icons displayed on 4K monitor scaled at 400% are 64x64 pixels.

Actual icon: https://raw.githubusercontent.com/end2endzone/ShellAnything/0.9.0/resources/icons/0.2.0.ico

**Describe the solution you'd like**
The next release should have a new icon design that is more modern. The icon should be 16x16 up to 64x64 to properly displayed on all monitor scaling factors.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by end2endzone** [comment]
@GasDauMin Hi! I would like to update ShellAnything main icon to a better version. Could you help me decide which one would be the most appropriate? I have comited a bunch of new icons at https://github.com/end2endzone/ShellAnything/tree/feature-issue171/resources/icons. If you could tell me your top 3 (or 5) that would help me make a decision.

**Comment by end2endzone** [comment]
64x64 (4K monitor at 400% scaling) :
![image](https://github.com/user-attachments/assets/397f5495-4195-4cee-a2a2-ae77bf8e3573)

16x16 (1080p at 100% scaling) :
![image](https://github.com/user-attachments/assets/9234640b-e295-4ba1-a2b8-f630a71d4168)


If you are using dark mode, I suggest you create a fake configuration file to see the icons over a dark background.

**Comment by GasDauMin** [comment]
In my personal opinion, the top three designs are:
1. Design 6 (cold)
2. Design 9
3. Design 6 (warm)

I know these selections may also be suitable for dark mode, as there is sufficient contrast between the dark gray background and the colors of the icons.

My apologies for keeping you waiting.

**Comment by end2endzone** [comment]
Test files:
```xml
<?xml version="1.0" encoding="utf-8"?>
<root>
  <shell>
    <menu separator="true" />
    <menu name="issue171">
      <menu name="design01.ico">        <icon path="${config.directory}\design01.ico" index="0" />        </menu>
      <menu name="design02.ico">        <icon path="${config.directory}\design02.ico" index="0" />        </menu>
      <menu name="design03.ico">        <icon path="${config.directory}\design03.ico" index="0" />        </menu>
      <menu name="design04.ico">        <icon path="${config.directory}\design04.ico" index="0" />        </menu>
      <menu name="design04-cold.ico">   <icon path="${config.directory}\design04-cold.ico" index="0" />   </menu>
      <menu name="design05.ico">        <icon path="${config.directory}\design05.ico" index="0" />        </menu>
      <menu name="design06.ico">        <icon path="${config.directory}\design06.ico" index="0" />        </menu>
      <menu name="design06-cold.ico">   <icon path="${config.directory}\design06-cold.ico" index="0" />   </menu>
      <menu name="design06-warm.ico">   <icon path="${config.directory}\design06-warm.ico" index="0" />   </menu>
      <menu name="design07.ico">        <icon path="${config.directory}\design07.ico" index="0" />        </menu>
      <menu name="design08.ico">        <icon path="${config.directory}\design08.ico" index="0" />        </menu>
      <menu name="design09.ico">        <icon path="${config.directory}\design09.ico" index="0" />        </menu>
    </menu>
    <menu separator="true" />
  </shell>
</root>	
```

Windows 10 light theme:
![issue171 - win10 light](https://github.com/user-attachments/assets/61a0d31b-5121-423d-9eb9-50d4a2cd0596)

Windows 11 dark theme:
![issue171 - win11 dark](https://github.com/user-attachments/assets/dc76abbc-fc3d-4c2f-b27c-61f63b2b2891)

**Comment by end2endzone** [comment]
My personal favorites are:
1. design06-warm
2. design06-cold
3. design04

but with a light theme, then there is also:
1. design09
2. design07
3. design09

I will also ask a few ppl around me and make a decision. Thank you for your feedback GasDauMin. Much appreciated.

**Comment by GasDauMin** [comment]
I have a new favorite, though. Before seeing it, I did not believe Design 3
with the dark theme would appear so appealing, which is why I did not rate
it initially. Now, I rank it first because this illustration best
demonstrates the tool's purpose in my opinion.

**Comment by olivier250cc** [comment]
I vote for design06-warm/design06-cold

**Comment by end2endzone** [comment]
Design 03 will be used.
