### ISSUE TITLE
Execute a console program without showing a window

### ISSUE THREAD

**Issue by mdnava** [end2endzone/ShellAnything#177]
As mentioned in https://github.com/end2endzone/ShellAnything/issues/108
I consider to be an important feature for ShellAnything to be able to run console programs without showing a terminal window.

As reference, KuShellExt has the `console="false"` option for this purpose.

For example, these context menus use ImageMagick commands to transform images, without showing a console:

![2024-09-17 21 28 39](https://github.com/user-attachments/assets/222389a8-55d2-426e-9520-4fd802271949)

Best regards!

**Comment by end2endzone** [comment]
This feature is now supported. If you would like to try the feature before the official release, use [the latest nightly-builds](https://ci.appveyor.com/project/end2endzone/shellanything/builds/50781132/artifacts) on AppVeyor.

**Comment by mdnava** [comment]
@end2endzone Understood, thank you..

I will try the update come November, as I'm currently pressured to handle a legal issue that should finalize this month.

If all goes well I'll start migrating to ShellAnything, but I do expect it'll take me a while 'cause I'm currently
using KuShellExt extensively. I'll probably migrate in batches, or maybe all at once if I can.

Best regards!
