### ISSUE TITLE
Find application a new name

### ISSUE THREAD

**Issue by end2endzone** [end2endzone/ShellAnything#33]
Proposed new names:
* Context Menu Composer.
* Action Menu Composer
* Shell Action Composer
 
Alternatives:
Top XX best editor "category":
* https://blogs.systweak.com/best-context-menu-editors-for-windows/
* https://www.thewindowsclub.com/remove-click-context-menu-items-editors
* https://www.maketecheasier.com/best-context-menu-editors/

Actual software:
* https://sourceforge.net/projects/contextmenushel/
* https://www.thewindowsclub.com/ultimate-windows-customizer
* https://www.thewindowsclub.com/right-click-context-menu-extender-for-windows-7-released
* https://www.thewindowsclub.com/context-menu-editor-for-windows-7-vista-released
* http://www.sordum.org/7615/easy-context-menu-v1-6/
* http://www.softpedia.com/get/Tweak/System-Tweak/BlueLife-ContextMenu.shtml
* http://www.softpedia.com/get/System/System-Miscellaneous/MenuMaid.shtml
* https://www.thewindowsclub.com/downloading-context-menu-editor
* https://winaero.com/download.php?view.62
* http://www.door2windows.com/ultimate-windows-context-menu-customizer-customize-context-menu-in-windows-xp-vista-7/
* https://www.lopesoft.com/index.php/en/download/filemenu-tools
* http://www.softpedia.com/get/System/OS-Enhancements/ContextEdit.shtml

**Comment by GasDauMin** [comment]
Maybe:
- Context Buddy
- Context Menu Extender (ContExtender, ContExtend, ContExt, ContE)
- Shell Action Extender (ShellExtender, ShellExtend, ShellExt, ShellE)

**Comment by end2endzone** [comment]
The names from file [library_names.txt](https://github.com/end2endzone/ShellAnything/blob/0.4.0/library_names.txt) :
- ShellAnything
- ShellIt
- ShellExView
- Shell Extension Warehouse
- Shell Extension Depot
- ShellExBin
- ShellExMill
- ShellForge
- Shell Extension Composer
- FileExplorer Forge
- FileExplorer Composer

Other names... 
- Extension Composer
- Explorer Extension Depot
- Action Menu Catalog

**Comment by end2endzone** [comment]
I like "Context Buddy" and "Context Menu Composer". 

I am not certain if I should change the name of the application anymore. At the time I wrote the issue, the project was pretty much unknown. I also had almost no download and no stars. I though that a better "catchy" name would make the application sound better. Now, looking at [the project statistics](https://hanadigital.github.io/grev/?user=end2endzone&repo=ShellAnything), the project starts to have more users and changing the name of the application might hurt more than dooing good.

Changing the name would have the following impact:
- The configuration directory would have to be changed from `%USERPROFILE%\ShellAnything` to something else. This would require an 'update' feature in the code that would migrate existing configurations to the new directory.
- The github url of the project will have to change. People links, favorites/bookmark will have to be updated. People that already uses ShellAnything might loose track of the project.
- All references to ShellAnything in the code would have to be changed.

**Comment by end2endzone** [comment]
The issue is now obsolete. There is now 2.1k downloads of "ShellAnything". The name won't change.
Closing.
