### ISSUE TITLE
Is this exclusively for adding entries to the Context Menu?

### ISSUE THREAD

**Issue by Unknow0059** [end2endzone/ShellAnything#57]
There is nothing I would like more than an easily customizable Windows 10 context menu, and this comes close. 

Programs love to clutter it with their entries, and it's not easy to remove them - much less the default entries - because it needs to be done manually and the entries differ according to the file extension.

So, could ShellAnything be used to remove entries, or is it exclusively for adding them?

**Comment by end2endzone** [comment]
I am sorry but no. ShellAnything only manages menu entries that it created. It cannot remove entries that were created by other programs.

>Programs love to clutter it with their entries, and it's not easy to remove them

I don't know if this is really helpful information but you can take a look at how ShellAnything registers itself to the system to get a hint on how to remove other program from the context menu. Basically, you can create menus by [modifying the registry for specific file extensions](https://www.groovypost.com/howto/add-any-program-windows-context-menu/) or by creating a dynamic dll called a Shell Extension. Most program creates shell extensions.

If you remove the references in the registry of a shell extension dll, you will remove any dynamic menus this dll was creating. A reboot or restard of all `explorer.exe` processes is required. You can take a look at how ShellAnything unregisters itself from the system in function `DllUnregisterServer()` in file [shellext.cpp, line 1215](https://github.com/end2endzone/ShellAnything/blob/master/src/shellext.cpp#L1215).
