### ISSUE TITLE
Syntax error in default.xml

### ISSUE THREAD

**Issue by GasDauMin** [end2endzone/ShellAnything#78]
According to [XML rules](https://www.w3.org/TR/REC-xml/#sec-comments), for compatibility reason it is better not to use '--' in the comments section.

![image](https://user-images.githubusercontent.com/2140205/103211364-aadf5700-4910-11eb-8d12-8bfa8af258e0.png)

**Comment by GasDauMin** [comment]
Sorry for overlaying branches I still lack the skills to work with git as advanced user. Probably one branch would have been enough for all my programming, i learn from my mistakes, next time i think i will do better. :-)

**Comment by end2endzone** [comment]
I think found out what you mean. The changes in PR #81 seems to also in changes of PR #82. Please allow me the time to take a look at this and I will be back to you ASAP.
