### ISSUE TITLE
Problems with Files > 2Gb

### ISSUE THREAD

**Issue by DBenS** [end2endzone/ShellAnything#96]
I'm facing a weird problem related to **file sizes greater then 2Gb**. See the below filenames:

Consultoria.20210921.rar
Consultoria.20210924.rar
Develop.NET.2021.08.25.rar
Develop.NET.2021.08.27.rar
Develop.NET.20210922.rar
Develop.NET.20210923.rar

They are related to "backup" sets and I'm trying to run my application (OBAKE) on them. But when selecting each one separately, the option "OBAKE" (my app) does not appear in the context menu if the file > 2Gb - even appearing to other files following the same filename syntax.

I believe the attached video can be more concise to explain what is going on here. 

**To Reproduce**
1- Create two files, one of them above 2Gb in size.
2- Try the context.

**Expected behavior**
The context menu to appear on all file size.

**Screenshots**
See the video attached

**Environment**
 - OS: Windows 
 - Version 8.1 Pro 64 bits up to date.

**Additional context**
Follows my code within the XML

```
<menu name="OBAKE">
<icon path="C:\OBAKEv6\Obake6.exe" index="0" />
<menu name="Encrypt Files">
<icon path="C:\OBAKEv6\Obake6.exe" index="0" />
<visibility class="file" exists="C:\OBAKEv6\Obake6.exe" maxfolders="0" />
<validity class="file" exists="C:\OBAKEv6\Obake6.exe" maxfolders="0" inverse="pattern" pattern="*.obkf???;C:\OBAKEv6*"/>
<actions>
	<property name="selection.multi.separator" value=";" />
	<file path="${env.USERPROFILE}\obk.in" encoding="utf-8">${selection.path}</file>
	<exec path="C:\OBAKEv6\Obake6.exe" arguments="&quot;/ef&quot; ${env.USERPROFILE}\obk.in" />
	<property name="selection.multi.separator" value="${line.separator}" />
</actions>
</menu>
</menu>

```

I appreciate your time and efforts to build this library and any help on this problem.
Kindest regards,.

https://user-images.githubusercontent.com/13090884/134744769-9e43b907-241d-43cf-80fc-03832785cc17.mp4

**Comment by end2endzone** [comment]
Hi. Thank you for using ShellAnything and providing feedback. It is much appreciated. It is always interesting to see how other people uses this software.

I have seen this problem before with other software that were also based on [end2endzone/RapidAssist](https://github.com/end2endzone/RapidAssist).
I think the cause of the issue is https://github.com/end2endzone/RapidAssist/issues/71. It was also discussed in details in another project of mine: https://github.com/end2endzone/bin2cpp/issues/55. If I am right, this is a strange coincidence. I fixed this issue today in RapidAssist.

Please allow me some time to update the dependency with the latest version. That should solve the problem.

**Comment by DBenS** [comment]
Certainly @end2endzone !
And my sincere congratulations for your work and efforts - I tried the same using .NET some years ago and I really understand the complexity of that job.

I'll be looking forward your fix.
Thank you!

**Comment by end2endzone** [comment]
Hi. I have updated ShellAnything to use RapidAssist 0.10.1. You can find new unofficial binaries at https://ci.appveyor.com/project/end2endzone/shellanything/builds/40929933/artifacts. I do have to stay at 0.6.0 for other testing purpose. Would you be kind enough to try it out and see if it fixes the issue ?

**Comment by DBenS** [comment]
> Hi. I have updated ShellAnything to use RapidAssist 0.10.1. You can find new unofficial binaries at https://ci.appveyor.com/project/end2endzone/shellanything/builds/40929933/artifacts. I do have to stay at 0.6.0 for other testing purpose. Would you be kind enough to try it out and see if it fixes the issue ?

Certainly @end2endzone !!
I appreciate your effort and fast fix.
I'll be back ASAP with my tests,
